# group: online-study-content
# \online-study-content\online-study-content-service\src\main\resources\bootstrap.yaml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.65:3306/xcplus_content?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: mysql

mybatis-plus:
  type-aliases-package: com.online_study.model.po
  mapper-locations: classpath:mapper/*.xml # mapper文件的默认路径也是这个
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出sql语句