# group: online-study-content
# \online-study-content\online-study-content-api\src\main\resources\bootstrap.yaml
server:
  servlet:
    context-path: /content
  port: 63040

# 设置项目本地配置优先，从而可以新启一个端口
spring:
  cloud:
    config:
      override-none: true