# group: online-study-project
# \online-study-media\online-study-media-service\src\main\resources\bootstrap.yaml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.65:3306/xcplus_media?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: mysql
  cloud:
    config:
      override-none: true

mybatis-plus:
  type-aliases-package: com.online_study.media.model.po
  mapper-locations: classpath:mapper/*.xml # mapper文件的默认路径也是这个
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出sql语句

# minio:
#   endpoint: http://192.168.101.65:9000
#   accessKey: minioadmin
#   secretKey: minioadmin
#   bucket:
#     files: mediafiles
#     videofiles: video
# xxl:
#   job:
#     admin:
#       addresses: http://192.168.101.65:8088/xxl-job-admin
#     executor:
#       appname: media-process-service
#       address:
#       ip:
#       port: 9999
#       logpath: /data/applogs/xxl-job/jobhandler
#       logretentiondays: 30
#     accessToken: default_token

# videoprocess:
#  ffmpegpath: D:/soft/ffmpeg/ffmpeg.exe
