# group: online-study-project
# \online-study-media\online-study-media-api\src\main\resources\bootstrap.yaml
server:
  servlet:
    context-path: /media
  port: 63050

# 设置项目本地配置优先，从而可以新启一个端口
spring:
  cloud:
    config:
      override-none: true